### ISSUE TITLE
Data Parsing / Individual Cache Policies? (For Rank Updates and other blocked progression)

### ISSUE THREAD

**Issue by rogueyoshi** [tsaibermelon/gg-struggle#1]
Does struggle get any of the data unencrypted by any chance? Maybe a separate cache policy for stuff pertaining to rank changes could be added so people could progress the twoer.

**Comment by fsantand** [comment]
I was about to post about this too, maybe a cache policy according depending on the endpoints, it could be mapped on a constant layer on a json file, or something of that style.

```javascript
const EXPIRE_TIME_TOWER_PROGRESSION = 1000 * 60 * 60 * 30 // Maybe 30 minutes is a right time
const EXPIRE_TIME_STATISTICS = 1000 * 60 * 60 * 60 * 24

const ENDPOINT_TO_CACHE_POLICY_MAPPING = {
    "statistics": EXPIRE_TIME_STATISTICS,
    "rank": EXPIRE_TIME_TOWER_PROGRESSION,
    ...
}
```
I do not know the exact endpoints of the GGST API, but maybe something like that would reduce the tower progression errors. Or maybe not even include caching for rank/tower progression, since it changes a lot.

Also, depending of the HTTP Method, it could discriminate the POST requests for the rank progressions, that should help something

**Comment by cybermelons** [comment]
> Does struggle get any of the data unencrypted by any chance?

Yup. The unencrypted responses and requests are dumped to their own file, named `<key>.<gameReq|ggResp>.dump`, where the key is a hash of the url, method, and raw request payload. Their metadata is stored in a sqlite db named `gg-struggle.db`. All this is found in `%TEMP%`

There are `requests` and `responses` tables in the db, and by joining them by the `dumpKey` column, we get the whole transaction.

Sample query

```
      SELECT
        req.dumpkey as dumpKey,
        req.url as url,
        req.method as method,
        req.headers as reqHeaders,
        req.timeStart as reqTimeStart,
        req.timeEnd as reqTimeEnd,

        resp.statusCode as respStatusCode,
        resp.headers as respHeaders,
        resp.payloadSize as respPayloadSize,
        resp.timeStart as respTimeStart,
        resp.timeEnd as respTimeEnd
      FROM requests AS req
      LEFT JOIN responses AS resp USING (dumpKey)
```
So with this you can get the metadata from the db, and read the raw payloads in the `dumps` directory.

**Comment by cybermelons** [comment]
I've drafted a sample implementation of a cache policy seen here: https://github.com/tsaibermelon/gg-struggle/blob/3fd846e0fedf556e2355fb0621841025dd49e9e3/server/local.json

It uses regexes to categorize the routes and the times are human-readable time strings.
