### ISSUE TITLE
Error reading Request: No such file or directory

### ISSUE THREAD

**Issue by Hyunades** [tsaibermelon/gg-struggle#10]
![Errorreadingrequest](https://user-images.githubusercontent.com/87450452/125697776-7b3e8949-8c1a-4288-aa6e-03908b4f51af.PNG)
Dump file contains: data=9295a0a002a5302e302e340391cd0100
Intalled the .exe as admin, launched the .exe as admin..
Tried launching the game, connection error, starts in offline mode.

**Comment by fsantand** [comment]
I fixed this error by deleting the gg-strive on %TEMP%

**Comment by Hyunades** [comment]
Doesnt work for me. 
A friend told me that it's because there's a space in the name of my user folder.

**Comment by supersosko** [comment]
fsantand's solution worked for me.
However, I deleted <code>gg-strive</code> in the <code>%TEMP%</code> directory

**Comment by fsantand** [comment]
> 
> 
> fsantand's solution worked for me.
> However, I deleted `gg-strive` in the `%TEMP%` directory

~I suppose that if the folder isn't found in the directory, then its created automatically, correct me if I'm wrong~ Oh no, but at least it did help

**Comment by Hyunades** [comment]
So, quick update cause in the end my friend helped me solving the whole thing.
1. I still didn't have a gg-strive in %TEMP% but a gg-struggle. Deleting it still didn't change a thing, however.
2. After redirecting my %TEMP% folder elsewhere (in D:\ because there I don't have the space in my folder directory path), it effectively worked. (Well with some the IP issue but that was fixed with the already present instructions)

**Comment by cybermelons** [comment]
Please open a new ticket if this is still an issue
