### ISSUE TITLE
uninstall

### ISSUE THREAD

**Issue by Haeleos** [tsaibermelon/gg-struggle#11]
Trying to remove this as it didn't work for me. Cannot connect to the network now. Following the instructions, it says to remove gg-struggle from certmgr.msc but I don't have any there, I have 3 entries of gst-game.guiltygear.com now though since I tried installing it 3 times. How do I remove this and go back to being able to play the game?

**Comment by Rem-02** [comment]
Try to use an IP from https://dns.google.com/query?name=ggst-game.guiltygear.com in the "data" fields
If you ping while this is installed it will return 127.0.0.1 (And this is not the right IP)

**Comment by Rem-02** [comment]
You have 3 entries of gst-game.guiltygear.com in your host file ?

**Comment by Haeleos** [comment]
![image](https://user-images.githubusercontent.com/14088561/125712930-a4782b98-ce69-4a93-82bd-de9e0574d102.png)
No the entries are in my certmgr one appeared each time I attempted an install, but they aren't named gg-struggle like it says in the Removal instructions.

**Comment by Haeleos** [comment]
In hosts file, it was pointing the non "real" server entry to 127.0.0.1, are you saying I should change the IP there?

**Comment by cuucas** [comment]
> 
> 
> In hosts file, it was pointing the non "real" server entry to 127.0.0.1, are you saying I should change the IP there?

Not the dev, but i managed to fully unninstal by deleting the "127.0.0.1 ggst-game.guiltygear.com" line entirely in the hosts file, and delete the three certificates "ggst-game.guiltygear.com" in your case

![image](https://user-images.githubusercontent.com/22038031/125717855-e235dde8-7c92-405d-9c3a-ec10ab260c46.png)

The image shows what's safe to delete

**Comment by cybermelons** [comment]
Running the installer and uninstaller in 1.5.0 will remove rogue host entries
