### ISSUE TITLE
Can't import gg-struggle-cert.pem

### ISSUE THREAD

**Issue by Jensegaense** [tsaibermelon/gg-struggle#14]
I am unable to import the gg-struggle-cert.pem into my Trusted Root Certification Authorities folder as it says that the file is password-protected.
I might just be an idiot, but I am unable to find any password that would fit here. The automatic installer seems to be unable to install the certification as well as I am experiencing similar issues there, even after using the installer there is no gg-struggle permit in the folder. Possible solutions mentioned in other threads yielded no results.
![GG-struggle-log](https://user-images.githubusercontent.com/87668378/126208505-f8020852-65c3-4998-9115-747ebb1f542c.png)

**Comment by cybermelons** [comment]
pass is `totsugeki` 🐬 

also, for the cert installation it needs admin privileges or it'll fail to install
