### ISSUE TITLE
Game can not connect to the Internet, even with local server running

### ISSUE THREAD

**Issue by AyyLmaoLol** [tsaibermelon/gg-struggle#7]
I would post this as a comment in the other thread, but I feel this is different as I'm not even getting an error. Important to note that this issue happens regardless of whether or not I run gg-struggle.exe as admin. It also happens when running in an admin PowerShell window.

My hosts file is modified, the local cache server is running, yet when I load the game up and try to get past the title screen it says it just can't connect. I can provide logs if you want, but the entirety of the log is

[2021-07-07T15:36:58.224] [INFO] default - [DB] Loading entries C:\Users\Erik\AppData\Local\Temp/gg-struggle/gg-struggle.db
[2021-07-07T15:36:58.237] [INFO] default - [PROXY] Listening on 443
[2021-07-07T15:36:58.237] [INFO] default - 

It doesn't even have a chance to give an error because it isn't grabbing the game traffic.

Checking in Resource Monitor tells me the game is definitely communicating on port 443, and the cache server is definitely listening on port 443, but it just doesn't seem to want to go.
![Pic with hosts file, local cache, and game](https://user-images.githubusercontent.com/87134311/124933067-95d73500-dfd1-11eb-9e99-0a489ba41b69.png)

I fear this has nothing to do with the program and is just something I've broken at some point, but any ideas would be appreciated.

**Comment by cybermelons** [comment]
I heard some people need to run it as admin. Can try it and confirm if that fixes it?

For security, some OSes block reserved ports like 443 (SSL) for security.

**Comment by AyyLmaoLol** [comment]
So I had Windows Firewall off, but I've turned it on and specifically allowed gg-struggle.exe both inbound and outbound, as well as port 443 on UDP and TCP. Running gg-struggle as admin still gets me the same result.

At this point, I'm just gonna install fresh Windows on another partition and see if it works.

**Comment by AyyLmaoLol** [comment]
Other Windows install worked. Not sure what the problem is, but it doesn't seem to be a problem with your program. I'll close this unless anyone else can think of anything.
