### ISSUE TITLE
network issues

### ISSUE THREAD

**Issue by cybermelons** [tsaibermelon/gg-struggle#8]
If gg-struggle suddenly stopped working, then you need to change the hosts to the real ip address.

TODO: write a script that patches the hosts using the real ip

see the hotfix in the [readme](https://github.com/tsaibermelon/gg-struggle).

**Comment by ManoShu** [comment]
I have made a simple application to update the hosts file (the intention was to launch gg-struggle but it was unsuccessful): https://github.com/ManoShu/StruggleTogether with a .exe build: https://github.com/ManoShu/StruggleTogether/releases/download/v0.1/StruggleTogether.exe Hope that helps someone

**Comment by cybermelons** [comment]
Fixed in #20
